alias: YOUR's To-Do Notification
description: To-do Notifications
trigger:
  - platform: time
    at: "08:00:00"
  - platform: time
    at: "12:00:00"
  - platform: time
    at: "15:00:00"
condition: []
action:
  - service: todo.get_items
    metadata: {}
    data:
      status: needs_action
    response_variable: todovar
    target:
      entity_id: todo.YOUR_to_do
  - if:
      - condition: template
        value_template: |-
          {%- for item in todovar['todo.YOUR_to_do']['items'] %}
            {% if 'due' in item%}
              {% set timeformat = "%Y-%m-%dT%H:%M:%S%z" if 'T' in item['due'] else  "%Y-%m-%d" %}
              {% set delta = as_local(strptime(item['due'], timeformat)) - today_at("00:00") %} 
              {% if delta.days == 0 %}
                True
                {% break %}
              {% elif delta.days < 0 %}
                True
                {% break %}
              {% endif %}
            {% endif %}
          {% endfor -%}
    then:
      - service: persistent_notification.create
        data:
          notification_id: TASK DUE
          title: A task is due today!
          message: A task is due today, check your to-do!!
        enabled: false
      - service: notify.mobile_app_YOURfone
        data:
          title: A task is due!
          message: |
            {%- for item in todovar['todo.YOUR_to_do']['items'] -%}
              {% if 'due' in item -%}
                {% set timeformat = "%Y-%m-%dT%H:%M:%S%z" if 'T' in item['due'] else  "%Y-%m-%d" -%}
                {% set delta = as_local(strptime(item['due'], timeformat)) - today_at("00:00") -%}
                {% if delta.days < 0 %} Task OVERDUE by {{ (delta.days | abs) }} day(s)  {{ '\n\n' -}} {{ item['summary'] }}
                {% elif delta.days == 0 %} Task due TODAY {{ '\n\n' -}} {{ item['summary'] }}
                {% endif -%}
              {% endif -%}
            {% endfor -%}
          data:
            ttl: 0
            priority: high
            tag: todo_notification
            actions:
              - action: URI
                title: Check your to-do list
                icon: mdi:note
                uri: /todo
mode: single
